namespace LHA.Shared.Domain
{
    /// <summary>
    /// Các loại ngôn ngữ
    /// </summary>
    public enum CLanguageType
    {
        English = 1,
        Spanish = 2,
        French = 3,
        German = 4,
        Italian = 5,
        Portuguese = 6,
        Russian = 7,
        Chinese = 8,
        Japanese = 9,
        Korean = 10,
        Arabic = 11,
        Hindi = 12,
        Bengali = 13,
        Urdu = 14,
        Turkish = 15,
        Vietnamese = 16,
        Thai = 17,
        Persian = 18,
        Malay = 19,
        Indonesian = 20,
        Swahili = 21,
        Dutch = 22,
        Greek = 23,
        Hebrew = 24,
        Polish = 25,
        Czech = 26,
        Slovak = 27,
        Hungarian = 28,
        Romanian = 29,
        Bulgarian = 30,
        Serbian = 31,
        Croatian = 32,
        Finnish = 33,
        Norwegian = 34,
        Swedish = 35,
        Danish = 36,
        Icelandic = 37,
        Filipino = 38,
        Tamil = 39,
        Telugu = 40,
        Marathi = 41,
        Gujarati = 42,
        Punjabi = 43,
        Kannada = 44,
        Malayalam = 45,
        Sinhala = 46,
        Nepali = 47,
        Burmese = 48,
        Khmer = 49,
        Lao = 50
    }
}